name: Build iPhone 5 IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python_version: '3.9'
          
      - name: Install Build Tools
        run: |
          pip install Cython==0.29.33
          pip install kivy-ios
          brew install autoconf automake libtool pkg-config
          
      - name: Build for iOS
        run: |
          toolchain build kivy
          toolchain create MyFirstApp .
          
      - name: Package IPA
        run: |
          mkdir Payload
          # This new command finds the .app folder wherever it is and copies it
          find . -name "*.app" -type d -exec cp -r {} Payload/ \;
          zip -r MyFirstApp.ipa Payload
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: MyFirstApp-IPA
          path: MyFirstApp.ipa
